gText_Birch_Welcome:: @ 82C897B
	.string "Hi! You're finally here!\p"
	.string "Welcome to the world of {COLOR POKEMON_COLOR}Pokémon{COLOR NO_COLOR}!\p"
	.string "My name is {COLOR CHARACTER_COLOR}Yinxing{COLOR NO_COLOR}.\p"
	.string "Around these parts I'm the local\n"
	.string "{COLOR CHARACTER_COLOR}Pokémon Professor{COLOR NO_COLOR}.\p"
	.string "$"

@ gText_ThisIsAPokemon is in strings.c

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "This is my {COLOR POKEMON_COLOR}Torchic{COLOR NO_COLOR}.\n"
	.string "Cute, right?\p"
	.string "He's just one of the many {COLOR POKEMON_COLOR}Pokémon{COLOR NO_COLOR} living\n"
	.string "far and wide in this world.\p"
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "But that's enough about me.$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Do you want to play as a {COLOR CHARACTER_COLOR}girl{COLOR NO_COLOR}?\n"
	.string "Or perhaps a {COLOR CHARACTER_COLOR}boy{COLOR NO_COLOR}?$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Sounds good.\n"
	.string "What's your {COLOR CHARACTER_COLOR}name{COLOR NO_COLOR}?$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "So, {COLOR CHARACTER_COLOR}{PLAYER}{COLOR NO_COLOR} is it?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Cool, cool.\p"
	.string "You're {COLOR CHARACTER_COLOR}{PLAYER}{COLOR NO_COLOR} who lives in the\n"
	.string "charming {COLOR LOCATION_COLOR}Yamaki Town{COLOR NO_COLOR}.\l"
	.string "I hear it's beautiful there!\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
